
version: '3.9'

services:
  nginx:
    build: ./ppv-platform/nginx
    ports:
      - "80:80"
    depends_on:
      - django
      - fastapi
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ppv
      POSTGRES_USER: ppvuser
      POSTGRES_PASSWORD: ppvpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  django:
    build: ./ppv-platform/django_app
    command: sh -c "python manage.py migrate && gunicorn django_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./ppv-platform/django_app:/app
    env_file:
      - ./ppv-platform/django_app/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  fastapi:
    build: ./ppv-platform/fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./ppv-platform/fastapi_app:/app
    env_file:
      - ./ppv-platform/fastapi_app/.env
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"


volumes:
  postgres_data:
