# Generated by Django 4.2.26 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='device_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
